### PR TITLE
Remove rails.

### PR DESCRIPTION
**Pull request by aboodman**
I received some feedback that it is more confusing than useful to have this extra level of abstraction at the point people are just trying to use Replicache which makes sense.

Our bigger sample apps will still use Rails, but this sample should be as minimal as possible.

### CODE REVIEW

**Comment by aboodman** [comment]
@cesara I was not able to land this because when I run, I get this error:

Screen Shot 2022-07-31 at 3 54 24 PM

This is because `@rocicorp/rails` is being included as a `devDependency` in `replicache-nextjs` but really needs to be a normal dependency since the code we put in the npm package relies on it.

I tried to make this fix myself but ran into a separate issue:

When I checkout `replicache-nextjs` and install, build, `npm link` it then run `replicache-todo` against it, I get this error:

Screen Shot 2022-07-31 at 3 59 00 PM

I am not sure what this is about. It looks like some bit of configuration telling it to use the postgres driver is not getting set right. is there an env var or something missing?

**Comment by aboodman** [comment]
PS @cesara when you fix this dependency in replicache-nextjs please make sure same issue doesn't occur with any other dev dep. Thinking here maybe of zod but there could be others.

**Comment by cesara** [comment]
@aboodman I pushed a new version of replicache-nextjs that resolved a lot of packaging issues. Comments are included in that PR. Your branch was good and I have found that `npm link` will sometimes cause errors that does not occur when running `npm pack` / `npm install .tgz`. I have started to use the later only.

**Comment by aboodman** [comment]
Epic! Thanks!

**Pull request merged**
